version: '3.8'
services:
 web:
   build: .
   volumes:
     - ./App:/app/App
   ports:
     - "8000:8000"
   environment:
     - DEBUG=True
   depends_on:
     - db

 db:
   image: postgis/postgis:14-3.3
   environment:
     - POSTGRES_DB=nightvibes
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   ports:
     - "5432:5432"

volumes:
 postgres_data: