# Generated by Django 4.2.7 on 2025-01-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_devicetoken_friendrequest_meetupping_notification_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['timestamp', 'venue'], name='App_checkin_timesta_1a1611_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['user', 'timestamp'], name='App_checkin_user_id_e3545f_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['visibility'], name='App_checkin_visibil_5a12ef_idx'),
        ),
    ]
