# Generated by Django 4.2.7 on 2025-01-28 02:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_location_lat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_location_lng',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
